{ inputs, ... }:
{
  den.aspects.packages = {
    nixos =
      { pkgs, ... }:
      let
        zen-browser = inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default;
      in
      {
        environment.systemPackages = with pkgs; [
          age
          air
          ansible
          appimage-run
          bat
          bitwarden-desktop
          blueman
          brightnessctl
          btop
          bun
          calibre
          cargo
          cliphist
          delta
          discord
          eza
          fastfetch
          fd
          fluxcd
          foot
          fzf
          gcc
          gh
          gh-markdown-preview
          ghostscript
          gimp
          git
          gnumake
          go
          go-task
          gopls
          gotestsum
          grim
          hugo
          hyprlock
          inotify-tools
          jq
          just
          k9s
          killall
          kitty
          kubectl
          kubectl-cnpg
          lazygit
          libnotify
          libsecret
          mako
          mangohud
          mermaid-cli
          neovim
          nh
          nil
          nix-index
          nixfmt
          nixpkgs-review
          nmgui
          nodejs
          obs-studio
          odin
          opencode
          openssl
          pavucontrol
          playerctl
          posting
          powershell
          presenterm
          python3
          restic
          ripgrep
          rustc
          rustfmt
          slurp
          sops
          spotify
          sqlc
          sqlite
          starship
          tailwindcss_4
          talosctl
          tdf
          terraform
          tesseract
          tree
          typescript
          typst
          unzip
          uv
          vlc
          wget
          wl-clipboard
          yazi
          yq-go
          zen-browser
          zig
          zoxide
        ];
      };
  };
}
