# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
notARepository: skip
gui:
    nerdFontsVersion: "3"
    border: rounded
    mouseEvents: false

    theme:
        activeBorderColor:
            - "#5ef1ff"
        inactiveBorderColor:
            - "#7b8496"
        searchingActiveBorderColor:
            - "#ff5ef1"
        optionsTextColor:
            - "#3c4048"
        selectedLineBgColor:
            - "#3c4048"
        cherryPickedCommitBgColor:
            - "#3c4048"
        cherryPickedCommitFgColor:
            - "#ff5ea0"
        unstagedChangesColor:
            - "#ffbd5e"
        defaultFgColor:
            - "#ffffff"
git:
    parseEmoji: true
    paging:
        colorArg: always
        useConfig: true
