format = """$model$tokens$cost$fill$turn$context$extension_status"""

[model]
style = "purple"
format = "[$model ]($style)"
symbol = ''

[tokens]
symbol = ''

[turn]
symbol = ''

[extension_status]
symbol = ''
icons = { "fallback" = '' }

[cost]
symbol = ''
format = "[ \\$$cost ]($style)"
[[cost.display]]
threshold = 0
style = "bold green"
hidden = false
[[cost.display]]
threshold = 0.5
style = "bold yellow"
hidden = false
[[cost.display]]
threshold = 1
style = "bold red"
hidden = false


[context]
format = "[ $percentage ]($style)"

[[context.display]]
threshold = 0
hidden = false
style = "bold green"
