source = ~/.config/hypr/$HOSTNAME.conf

general {
    fail_timeout = 500
}

background {
    path = /tmp/current_wallpaper
    blur_passes = 1
    blur_size = 0
    brightness = 0.5
}

label {
    monitor = $MONITOR
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, .65)
    font_size = 22
    font_family = Geist
    position = 0, 420
}

label {
    monitor = $MONITOR
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(255, 255, 255, .65)
    font_size = 90
    font_family = Geist
    position = 0, 340
}

input-field {
    monitor = $MONITOR
    size = 300, 50
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgba(255, 255, 255, 0.6)
    placeholder_text =
    valign = bottom
    position = 0, 70
}
